// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
window.application = application

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import CodeController from "./code_controller"
application.register("code", CodeController)

import DarkController from "./dark_controller"
application.register("dark", DarkController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import PortalController from "./portal_controller"
application.register("portal", PortalController)

import SearchController from "./search_controller"
application.register("search", SearchController)
